<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="6" hostname="Shadmans-MBP.home" name="com.dunkin.shadman.onlineStore.testScripts.Test1" tests="10" failures="0" timestamp="22 Oct 2018 02:20:53 GMT" time="0.846" errors="2">
  <testcase name="loginTest3" time="0.062" classname="com.dunkin.shadman.onlineStore.testScripts.Test1">
    <skipped/>
  </testcase> <!-- loginTest3 -->
  <testcase name="loginTest1" time="0.079" classname="com.dunkin.shadman.onlineStore.testScripts.Test1">
    <skipped/>
  </testcase> <!-- loginTest1 -->
  <testcase name="loginTest3" time="0.028" classname="com.dunkin.shadman.onlineStore.testScripts.Test1">
    <skipped/>
  </testcase> <!-- loginTest3 -->
  <testcase name="loginTest1" time="0.038" classname="com.dunkin.shadman.onlineStore.testScripts.Test1">
    <error type="junit.framework.AssertionFailedError">
      <![CDATA[junit.framework.AssertionFailedErrorat junit.framework.Assert.fail(Assert.java:47)at junit.framework.Assert.assertTrue(Assert.java:20)at junit.framework.Assert.assertTrue(Assert.java:27)at com.dunkin.shadman.onlineStore.helper.assertion.AssertionHelper.makeFalse(AssertionHelper.java:48)at com.dunkin.shadman.onlineStore.testScripts.Test1.loginTest1(Test1.java:17)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.retryFailed(Invoker.java:829)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1000)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </error>
  </testcase> <!-- loginTest1 -->
  <testcase name="loginTest1" time="0.061" classname="com.dunkin.shadman.onlineStore.testScripts.Test1">
    <skipped/>
  </testcase> <!-- loginTest1 -->
  <testcase name="loginTest" time="0.073" classname="com.dunkin.shadman.onlineStore.testScripts.Test1"/>
  <testcase name="loginTest3" time="0.295" classname="com.dunkin.shadman.onlineStore.testScripts.Test1">
    <error type="junit.framework.AssertionFailedError">
      <![CDATA[junit.framework.AssertionFailedErrorat junit.framework.Assert.fail(Assert.java:47)at junit.framework.Assert.assertTrue(Assert.java:20)at junit.framework.Assert.assertTrue(Assert.java:27)at com.dunkin.shadman.onlineStore.helper.assertion.AssertionHelper.makeFalse(AssertionHelper.java:48)at com.dunkin.shadman.onlineStore.testScripts.Test1.loginTest3(Test1.java:27)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.retryFailed(Invoker.java:829)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1000)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </error>
  </testcase> <!-- loginTest3 -->
  <testcase name="loginTest1" time="0.053" classname="com.dunkin.shadman.onlineStore.testScripts.Test1">
    <skipped/>
  </testcase> <!-- loginTest1 -->
  <testcase name="loginTest2" time="0.082" classname="com.dunkin.shadman.onlineStore.testScripts.Test1"/>
  <testcase name="loginTest3" time="0.075" classname="com.dunkin.shadman.onlineStore.testScripts.Test1">
    <skipped/>
  </testcase> <!-- loginTest3 -->
</testsuite> <!-- com.dunkin.shadman.onlineStore.testScripts.Test1 -->
